/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "BasePaymaster"): TruffleContracts.BasePaymasterContract;
      require(
        name: "BaseRelayRecipient"
      ): TruffleContracts.BaseRelayRecipientContract;
      require(name: "BatchForwarder"): TruffleContracts.BatchForwarderContract;
      require(name: "Forwarder"): TruffleContracts.ForwarderContract;
      require(
        name: "GsnEip712Library"
      ): TruffleContracts.GsnEip712LibraryContract;
      require(name: "IForwarder"): TruffleContracts.IForwarderContract;
      require(name: "IPaymaster"): TruffleContracts.IPaymasterContract;
      require(name: "IPenalizer"): TruffleContracts.IPenalizerContract;
      require(name: "IRelayHub"): TruffleContracts.IRelayHubContract;
      require(
        name: "IRelayRecipient"
      ): TruffleContracts.IRelayRecipientContract;
      require(name: "IStakeManager"): TruffleContracts.IStakeManagerContract;
      require(
        name: "IVersionRegistry"
      ): TruffleContracts.IVersionRegistryContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(
        name: "PayableWithEmit"
      ): TruffleContracts.PayableWithEmitContract;
      require(name: "Penalizer"): TruffleContracts.PenalizerContract;
      require(name: "RelayHub"): TruffleContracts.RelayHubContract;
      require(name: "StakeManager"): TruffleContracts.StakeManagerContract;
      require(name: "TestForwarder"): TruffleContracts.TestForwarderContract;
      require(
        name: "TestForwarderTarget"
      ): TruffleContracts.TestForwarderTargetContract;
      require(
        name: "TestPaymasterConfigurableMisbehavior"
      ): TruffleContracts.TestPaymasterConfigurableMisbehaviorContract;
      require(
        name: "TestPaymasterEverythingAccepted"
      ): TruffleContracts.TestPaymasterEverythingAcceptedContract;
      require(
        name: "TestPaymasterOwnerSignature"
      ): TruffleContracts.TestPaymasterOwnerSignatureContract;
      require(
        name: "TestPaymasterPreconfiguredApproval"
      ): TruffleContracts.TestPaymasterPreconfiguredApprovalContract;
      require(
        name: "TestPaymasterStoreContext"
      ): TruffleContracts.TestPaymasterStoreContextContract;
      require(
        name: "TestPaymasterVariableGasLimits"
      ): TruffleContracts.TestPaymasterVariableGasLimitsContract;
      require(name: "TestRecipient"): TruffleContracts.TestRecipientContract;
      require(
        name: "TestRelayHubValidator"
      ): TruffleContracts.TestRelayHubValidatorContract;
      require(
        name: "TestRelayWorkerContract"
      ): TruffleContracts.TestRelayWorkerContractContract;
      require(name: "TestUtil"): TruffleContracts.TestUtilContract;
      require(
        name: "VersionRegistry"
      ): TruffleContracts.VersionRegistryContract;
    }
  }
}
