#!/bin/bash -e
(cd .. && ./dock/run.sh make build-server)
cd `dirname $0`
DIR=../build/dockrelay
rm -rf $DIR
mkdir $DIR
cp -a * $DIR
mkdir -p $DIR/relay/bin
cp ../build/dock-builD/server/bin/* $DIR/relay/bin/
cd $DIR
docker build -t tabookey/dockrelay .

echo 'Docker image build. use "docker push" to publish'
