#!/bin/bash -e 
#starts relay in the background.
cd `dirname $0`

#unique hostname. used for dyndns registration (must be available by our dns config)
HOST=${HOST=`hostname`}
PORT=${PORT=443}

case "$1" in
	run)	DETACH=-d; CMD="" ;;
	bash)	DETACH=""; CMD=$* ;;
	*)
		echo "usage: $0 run|bash"
		echo " - run - run the docker in detached mode."
		echo " - shell - start interactive shell in docker. need to /sbin/my_init to start the relay"
		echo
		echo ' folder "relay/config" contains configuration file.'
		echo ' state is saved in "./.data", so it docker can be killed and restarted'
		echo ' latest server log is always "./data/logfile.txt"'
		echo " (prefix with USE_SSH=1 to enable SSH into the docker)"
		echo
		exit 1 ;;
esac

if [ -t 1 ]; then TTY="-ti" ; else TTY="-i"; fi
test -n "USE_SSH" && SSH="-p 2222:22 -v /tmp/auth.sh:/tmp/auth.sh "
echo "echo `cat $HOME/.ssh/id_rsa.pub` >> /root/.ssh/authorized_keys" > /tmp/auth.sh 
chmod +x /tmp/auth.sh

name=relayd-$PORT
docker run $DETACH  --rm  $TTY --name $name -v `pwd`/.data:/relay/data -v `pwd`/relay/config:/relay/config $SSH -p 80:80 -p $PORT:443 -e HOST=$HOST -e PORT=$PORT tabookey/dockrelay $CMD

test -n "$DETACH" && echo "started docker image $name"

