#!/bin/bash -e

branch=`git branch | sed -ne 's/[*] *//p'`

title=`git log --format="%h %ad, %an, %s"|head -1 `

#do nothing on non-master branch
#test branch != 'master' && exit 0

echo branch: $branch commit: $title
echo ''
#echo $title | grep OG-[0-9]
echo $title | ggrep -E  '\w\w+-[0-9]|dependabot'

