#should be launched with:
# docker-compose up -d

version: '3'

services:

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '443:443'
      - '80:80'
    restart: always
    environment:
      DOMAINS: '${HOST} -> http://gsn'
      STAGE: ${HTTPS_STAGE}

  gsn:
    ports: [ '8080:80' ] #bypass https-portal
    image: opengsn/jsrelay:3.0.0-beta.2
    restart: on-failure

    # /app/data - relay specific folder
    # /app/config - read-only config folder
    # /app/data/manager - shared manager folder of all relays
    volumes:
      - ./gsndata/gsn:/app/data
      - ./gsndata/manager:/app/data/manager
      - ./config:/app/config:ro

    environment:
      url: https://${HOST}/
      port: 80
      workdir: /app/data
      config: /app/config/gsn-relay-config.json
