#!/bin/bash -xe

# performs SSH into given machine and executes a DC command on it with args
if [ -z $2 ]; then
cat <<EOF
rdc - remote docker-compose (on google cloud)
usage: $0 {user@host} {docker-compose params}

EOF
exit 1
fi

host=$1
shift
args="$@"


DC='docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$PWD:$PWD" -w="$PWD" docker/compose:1.24.0'

ssh $host $DC $args 
