#!/bin/bash 

exited=
function onexit() {
    test -z "$exited" && docker rm -f gsn-dock
}

trap onexit EXIT

if [ "$1" == "with-ganache" ]; then
	ARG=/start-relay-with-ganache.sh
	PORT="-p 8545:8545"
else
	ARG=
	PORT=
fi

docker run -t --name gsn-dock --rm -p 8090:8090 $PORT tabookey/gsn-dev-server:v0.4.1 $ARG
exited=1
