#!/bin/bash
#start hardhat-node in a way that "run-with-testrpc" will work
# (it looks up for "Listening on" string, to determine when the node is up)
trap "pkill -9 -f 'hardhat node'" EXIT
npx hardhat node $*| tee hardhat.log | sed -u 's/Started HTTP and WebSocket/Listening on/'
