#!/bin/bash -xe
rm -rf ./dist/
yarn extract_abi
yarn generate
tsc
mkdir -p helpers/compiled/

CONTRACTS="RelayHub StakeManager Penalizer TestPaymasterEverythingAccepted"
BUILDFOLDER=./build/contracts
OUTFOLDER=./helpers/compiled/
for c in $CONTRACTS ; do cp $BUILDFOLDER/$c.json $OUTFOLDER ; done
