#!/bin/bash -e

rm -rf ./dist/
yarn generate

mkdir -p src/cli/compiled/

CONTRACTS="RelayHub StakeManager Penalizer Forwarder VersionRegistry TestPaymasterEverythingAccepted"
BUILDFOLDER=./build/contracts
OUTFOLDER=./src/cli/compiled/
for c in $CONTRACTS; do
  echo copy $OUTFOLDER/$c.json
  cp $BUILDFOLDER/$c.json $OUTFOLDER
done


#these files are created for packing only (removed by "postpack")
for c in RelayProvider RelayClient GSNConfigurator GsnTestEnvironment; do
  echo gen ./$c.ts:
  (echo "// generated during pack";echo "export * from './src/relayclient/$c'") > $c.ts
done

tsc
#we have in our package.json: "bin": { "gsn": "dist/src/cli/commands/gsn.js" }
chmod a+rx dist/src/cli/commands/gsn.js

cp -r types dist/
