#!/bin/bash -e

rm -rf ./dist/
yarn extract_abi
yarn generate

mkdir -p helpers/compiled/

CONTRACTS="RelayHub StakeManager Penalizer TrustedForwarder TestPaymasterEverythingAccepted"
BUILDFOLDER=./build/contracts
OUTFOLDER=./helpers/compiled
for c in $CONTRACTS; do
  echo copy $OUTFOLDER/$c.json
  cp $BUILDFOLDER/$c.json $OUTFOLDER
done


for c in GsnDevProvider RelayProvider RelayClient GSNConfigurator; do
  echo gen ./$c.ts:
  (echo "// generated during pack";echo "export * from './src/relayclient/$c'") > $c.ts
done

tsc
