#!/bin/bash -e

report=coverage/report.txt
tests="test/relay_hub_test.js test/recipient_utils_test.js"

npm run clean-coverage 
MODE=coverage npx truffle --network coverage test $tests
exitcode=$?
istanbul report text --color > $report

#dump report on errors too, but only if there is SOME coverage...
if grep -q "[.]sol" $report; then

cat $report
istanbul report html 
echo to view: open coverage/index.html

fi

exit $exitcode
